fix(build): skip empty compilation errors
When I added the following performance option:
```
  configureWebpack: {
    // merged with the internal config
    performance: {
      hints: "error",
      maxEntrypointSize: 1
    }
  },
```
The build failed, but the error message was not helpful:
```
(node:12752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stack' of undefined
```

This is because the first `stats.compilation.errors` was an empty array (the actual error was in the second `stats`).

Moreover such an error does not itself contains an error (hence the `err.error || err`).